# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Figment of Imagination
author: Kia Hosseini
expertise: Software Engineer
email: kia.hosseini7@gmail.com
description: >
    Notes from a depressed guy with motivated feelings!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kiahosseini.github.io" # the base hostname & protocol for your site
twitter_username: KiaHosseini
github_username:  kiahosseini

# Build settings
markdown: kramdown
gems:
 - jekyll-coffeescript
